# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638369960a2b4992fc996b5a866b046219a1d929e98cafb21b9bf64f1b50620cc2a3ae723eb63cb0e73f329e145dcb2ef36c224007b9d6faa344eeb6bc1662f0

test:
  secret_key_base: deabf1b2d56a5fca24669d2a5fb8e70df63542b7c01b389b0d65b1d2c94d3822d6ef46ceffba5b2c2950864e8a7f45fce7771f803ea403690258cb9198d4e1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
