# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1df19ac533fcafb8510bbbf70c6c071c8c7e372e6a724c772f62afdcae3ef2c56eed9f03bbc4ea823902f1c9e2cd635104d51bb22ea9853504bc0b1528d08bf1

test:
  secret_key_base: 03bac5ee320487d6d4f3df233c63da0b389f53c92001bd80c6e68618052ced527909c3577d8ba6dd1aeab675250caff17701b613199c8293de62c581aea6c640

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
